name: even_managment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  flutter_pdfview: ^1.3.3
  path_provider: ^2.1.4

flutter:
  uses-material-design: true
  assets:
   - asstes\dreem_job.png 
   - asstes\success_man.png
   - asstes\Screenshot_2024-10-08_193219-removebg-preview.png
   - asstes\Screenshot_2024-10-08_194043-removebg-preview.png
   - asstes\job icon.png


